export default {

    Login: `user/login`,
    SearchAdmin: `admin/search`,
    InvestmentSave: `invest/save`,
    RateSave: `rate/save`,
    RateSearch: `rate/search`,
    InvestSearch: `invest/search`,
    RemainSearch: `remain/search`,
    TransactionSave: `transaction/save`,
    TransactionList: `transaction/search`, 
    TransactionDelete: `transaction/delete`,
    TransactionTransfer: `transaction/transfer`,
    TransactionSale: `transaction/sale`,
    HistorySearch: `history/search`,
    NotiSearch: `noti/search`,
    StorageSearch: `storage/search`,

    AccountSearch: `account/search`,
    AccountSearchWithRemain: `account/search-with-remain`,
    AccountSearchWithMatch: `account/search-with-match`,
    DepositSave: `deposit/save`,
    MatchSave: `match/save`,
    MatchResult: `match/result`,
    WithdrawSave: `withdraw/save`,
    DashboardGetRemain: `dashboard/get-remain`,
    DashboardDepositWithdraw: `dashboard/deposit-withdraw`,
    DashboardWithdraw: `dashboard/get-withdraw`,
    MatchSearch: `match/search`,
    MatchDelete: `match/delete`,
    MatchHistory: `match-history/search`,
    ResetPassword: `reset/password`,
    
};